config/routes.rb
Rails.application.routes.draw do
  get 'weather/dashboard'
  post 'weather/address'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "weather#dashboard"
end

app/models/application_record.rb
# frozen_string_literal: true

# Put application record methods here
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

# This controller takes the User input data and formats an address that is used to get the
# the forecast data that is then displayed in the view.
class WeatherController < ApplicationController
  def dashboard
    return if session[:address].blank?

    latlong_api = GeocoderApi.new(session[:address])
    latlong = latlong_api.lat_long_from_address
    @display_name = latlong_api.display_name_from_address
    @forecast_data = get_forecast_data(latlong)
  end

  def address
    session[:address] = ''
    param_array = load_param_array(params)
    format_address(param_array) if param_array.length.positive?
    redirect_back_or_to weather_dashboard_path
  end

  private

  def get_forecast_data(latlong)
    @from_cache = true
    Rails.cache.fetch("#{latlong[:lat]}#{latlong[:long]}", expires_in: 30.minutes, race_condition_ttl: 10.seconds) do
      @from_cache = false
      weather_api = NationalWeatherApi.new(latlong)
      weather_api.weather_by_lat_long
    end
  end

  def format_address(param_array)
    param_array.each do |param|
      session[:address] = if session[:address].blank?
                            param
                          else
                            "#{session[:address]},#{param}"
                          end
    end
  end

  def load_param_array(params)
    param_array = []
    param_array.push(params['city']) unless params['city'].blank?
    param_array.push(params['state']) unless params['state'].blank?
    param_array.push(params['zip']) unless params['zip'].blank?
    param_array
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Put application helper methods here
module ApplicationHelper
end

app/helpers/weather_helper.rb
# frozen_string_literal: true

# Put weather helper methods here
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/dashboard.html.erb
<h1>Weather</h1>

<%= form_tag weather_address_path do %>
    <%= label_tag(:city, "City:") %>
    <%= text_field_tag(:city) %><br>
    <%= label_tag(:state, "State:") %>
    <%= text_field_tag(:state) %><br>
    <%= label_tag(:zip, "Zip:") %>
    <%= number_field_tag(:zip) %><br><br>
    <%= submit_tag("Get The Forecast") %>
<% end %>
<br>

<% if !@forecast_data.blank? %>
    <p> 7 Day Weather Forecast for <%= @display_name %> 
        <% if @from_cache %>
            FROM CACHE
        <% end %>
    </p>
    <% @forecast_data["properties"]["periods"].each do |period| %>
        <p> <%= period["name"] %> </p>
        <dd><p>Temperature: <%= period["temperature"] %> </p>
            <p>Short Forecast: <%= period["shortForecast"] %> </p>
        </dd>
    <% end %>
<% else %>
    <code> Please enter address information. Only US addresses are accepted. </code>
<% end %>